apiVersion: v1
kind: Secret
metadata:
  name: registry-creds
  namespace: clearing-house
type: Opaque
data:
  revocationListURL: ${REGISTRY_REVOCATION_LIST_URL}
  trustedIssuersURL: ${REGISTRY_TRUSTED_ISSUERS_URL}
  x509Certificate: ${REGISTRY_X509_CERTIFICATE}
  privateKey: ${REGISTRY_PRIVATE_KEY}
---

