apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-configmap
  namespace: clearing-house
data:
  PORT: "3000"
  MONGO_DATABASE: "trust-anchor-registry"
  MONGO_HOST: "registry-mongo.clearing-house.svc.cluster.local"
  MONGO_PORT: "27017"
  BASE_URL: "https://registry.${PUBLIC_NODE_DOMAIN}"
  evsslonly: "true"
---
