apiVersion: v1
kind: ConfigMap
metadata:
  name: compliance-configmap
  namespace: clearing-house
data:
  REGISTRY_URL: "https://registry.${PUBLIC_NODE_DOMAIN}"
  BASE_URL: "https://compliance.${PUBLIC_NODE_DOMAIN}"
  SD_STORAGE_BASE_URL:  "https://example-storage.lab.gaia-x.eu"
  SD_STORAGE_API_KEY: "Nothing"
  APP_PATH: ""
  TLS: "true"
  production: "true"
  dburl: bolt://compliance-memgraph-service:7687
---

